version: '3.7'

services:

  database:
    container_name: database
    hostname: database
    image: postgres:12
    ports:
    - 5432:5432
    environment:
    - TZ=America/New_York
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3

  opennms:
    container_name: opennms
    hostname: opennms
#   image: agalue/horizon:26.0.0 # To avoid NMS-12688
    image: opennms/horizon:26.0.0
    depends_on:
    - database
    command: [ -s ]
    ports:
    - 8980:8980
    - 8101:8101
    - 4444:4444/udp
    volumes:
    - ./opennms-overlay:/opt/opennms-etc-overlay
    environment:
    - TZ=America/New_York
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: curl -f -I http://localhost:8980/opennms/login.jsp
      interval: 1m
      timeout: 5s
      retries: 3
 
  # Generate random numbers for heart rate and step count using NX-OS Telemetry Object
  generator:
    container_name: generator
    hostname: generator
    image: agalue/fhir-sample-generator
    depends_on:
    - opennms
    environment:
    - TZ=America/New_York
    - TARGET=opennms:4444
    - FREQUENCY=30s

