version: '3.7'

volumes:

  zookeeper:
  kafka:

services:

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    hostname: zookeeper
    volumes:
    - zookeeper:/data
    environment:
    - TZ=America/New_York
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper:2888:3888
    - JMXLOCALONLY=false
    - JMXDISABLE=false
    - JMXPORT=9998
    - JMXAUTH=false
    - JMXSSL=false
    healthcheck:
      test: echo stat | nc zookeeper 2181
      interval: 30s
      timeout: 5s
      retries: 3

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka
    hostname: kafka
    depends_on:
    - zookeeper
    volumes:
    - kafka:/kafka
    environment:
    - TZ=America/New_York
    - KAFKA_BROKER_ID=1
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181/kafka
    - KAFKA_NUM_PARTITIONS=1
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_DEFAULT_REPLICATION_FACTOR=1
    - KAFKA_MIN_INSYNC_REPLICAS=1
    - JMX_PORT=9999
    - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9999
    ports:
    - 9092:9092
    healthcheck:
      test: nc -z localhost 9092
      interval: 30s
      timeout: 5s
      retries: 3

  manager:
    image: hlebalbau/kafka-manager:2.0.0.2
    container_name: manager
    hostname: manager
    depends_on:
    - kafka
    ports:
    - 9000:9000 
    environment:
    - TZ=America/New_York
    - ZK_HOSTS=zookeeper:2181
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9000 || exit 1
      interval: 1m
      timeout: 5s
      retries: 3

  generator:
    container_name: generator
    hostname: generator
    image: agalue/fhir-sample-generator-kafka
    depends_on:
    - kafka
    environment:
    - TZ=America/New_York
    - BOOTSTRAP=kafka:9092
    - TOPIC=metrics
    - FREQUENCY=30s

  # Make sure to set FORWARDER_EVENT_HUB_CONNECTION_STR on your host prior start the environment
  forwarder:
    container_name: forwarder
    hostname: forwarder
    image: agalue/fhir-eventhub-forwarder
    depends_on:
    - generator
    environment:
    - TZ=America/New_York
    - BOOTSTRAP_SERVERS=kafka:9092
    - SOURCE_TOPIC=metrics
    - GROUP_ID=forwarder
    - EVENT_HUB_CONNECTION_STR=${FORWARDER_EVENT_HUB_CONNECTION_STR:?}

  # Make sure to set CONSUMER_EVENT_HUB_CONNECTION_STR on your host prior start the environment
  consumer:
    container_name: consumer
    hostname: consumer
    image: agalue/fhir-sample-consumer
    depends_on:
    - forwarder
    environment:
    - TZ=America/New_York
    - EVENT_HUB_CONNECTION_STR=${CONSUMER_EVENT_HUB_CONNECTION_STR:?}

